// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, Status) {
  StatusPaused = 0,
  StatusReadyToPrint = 1,
  StatusUnknown = 2,
};

/// Wrapper for Status to allow for nullability.
@interface StatusBox : NSObject
@property(nonatomic, assign) Status value;
- (instancetype)initWithValue:(Status)value;
@end

typedef NS_ENUM(NSUInteger, Cause) {
  CausePartialFormatInProgress = 0,
  CauseHeadCold = 1,
  CauseHeadOpen = 2,
  CauseHeadTooHot = 3,
  CausePaperOut = 4,
  CauseRibbonOut = 5,
  CauseReceiveBufferFull = 6,
  CauseNoConnection = 7,
  CauseUnknown = 8,
};

/// Wrapper for Cause to allow for nullability.
@interface CauseBox : NSObject
@property(nonatomic, assign) Cause value;
- (instancetype)initWithValue:(Cause)value;
@end

@class StatusInfo;

@interface StatusInfo : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithStatus:(Status)status
    cause:(Cause)cause;
@property(nonatomic, assign) Status status;
@property(nonatomic, assign) Cause cause;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetMessagesCodec(void);

@protocol ZebraPrinting
/// @return `nil` only when `error != nil`.
- (nullable StatusInfo *)checkPrinterStatusOverTCPIPWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpZebraPrinting(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ZebraPrinting> *_Nullable api);

extern void SetUpZebraPrintingWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ZebraPrinting> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
