// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "Messages.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@implementation StatusBox
- (instancetype)initWithValue:(Status)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation CauseBox
- (instancetype)initWithValue:(Cause)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@interface StatusInfo ()
+ (StatusInfo *)fromList:(NSArray<id> *)list;
+ (nullable StatusInfo *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation StatusInfo
+ (instancetype)makeWithStatus:(Status)status
    cause:(Cause)cause {
  StatusInfo* pigeonResult = [[StatusInfo alloc] init];
  pigeonResult.status = status;
  pigeonResult.cause = cause;
  return pigeonResult;
}
+ (StatusInfo *)fromList:(NSArray<id> *)list {
  StatusInfo *pigeonResult = [[StatusInfo alloc] init];
  StatusBox *boxedStatus = GetNullableObjectAtIndex(list, 0);
  pigeonResult.status = boxedStatus.value;
  CauseBox *boxedCause = GetNullableObjectAtIndex(list, 1);
  pigeonResult.cause = boxedCause.value;
  return pigeonResult;
}
+ (nullable StatusInfo *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [StatusInfo fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    [[StatusBox alloc] initWithValue:self.status],
    [[CauseBox alloc] initWithValue:self.cause],
  ];
}
@end

@interface nullMessagesPigeonCodecReader : FlutterStandardReader
@end
@implementation nullMessagesPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[StatusBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 130: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[CauseBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 131: 
      return [StatusInfo fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface nullMessagesPigeonCodecWriter : FlutterStandardWriter
@end
@implementation nullMessagesPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[StatusBox class]]) {
    StatusBox *box = (StatusBox *)value;
    [self writeByte:129];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[CauseBox class]]) {
    CauseBox *box = (CauseBox *)value;
    [self writeByte:130];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[StatusInfo class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface nullMessagesPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation nullMessagesPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[nullMessagesPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[nullMessagesPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *nullGetMessagesCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    nullMessagesPigeonCodecReaderWriter *readerWriter = [[nullMessagesPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpZebraPrinting(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ZebraPrinting> *api) {
  SetUpZebraPrintingWithSuffix(binaryMessenger, api, @"");
}

void SetUpZebraPrintingWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ZebraPrinting> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.zsdk.ZebraPrinting.checkPrinterStatusOverTCPIP", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(checkPrinterStatusOverTCPIPWithError:)], @"ZebraPrinting api (%@) doesn't respond to @selector(checkPrinterStatusOverTCPIPWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        StatusInfo *output = [api checkPrinterStatusOverTCPIPWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
